const express = require("express")
const mongoose = require("mongoose")
const cors = require("cors")
const app = express()
app.use(express.json())
app.use(cors())
const userRouter = require("../routes/users.js")
const recipeRouter = require("../routes/recipes.js")
require("dotenv").config()
app.use("/auth",userRouter)
app.use("/recipe",recipeRouter)
mongoose.connect(`mongodb+srv://admin:${process.env.PASS}@cluster0.kjrrtsk.mongodb.net/recipes?retryWrites=true&w=majority`)
app.listen(3001,()=>{
    console.log("Server Started")
})